version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  run_tests:
    docker:
      - image: circleci/node:8.11
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm run test

  deploy:
    machine:
        enabled: true
    environment:
      - HEROKU_APP: $HEROKU_APP
    steps:
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/l3digital.git master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - run_tests:
          requires:
            - checkout_code
      - deploy:
          requires:
            - run_tests
