version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/l3digital
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/l3digital/node_modules

  run_linting:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/l3digital
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-

      - run:
          name: Lint
          command: npm run lint

  run_tests:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/l3digital
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-

      - run:
          name: Test
          command: npm run test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - run_linting:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - run_linting
