defaults: &defaults
    docker:
        - image: circleci/node:8.11
    working_directory: ~/l3digital

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/l3digital/node_modules
      - persist_to_workspace:
          root: .
          paths: .

  run_linting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/l3digital
      - run:
          name: Lint
          command: npm run lint

  unit_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/l3digital
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - run_linting:
          requires:
            - checkout_code
      - unit_tests:
          requires:
            - run_linting
